name: flutter_application_vegatables
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.15.1 <3.0.0"
  
  cupertino_icons: ^1.0.2
  
dependencies:  
  flutter_test:
    sdk: flutter
  tflite: ^1.1.2
  image_picker: ^0.8.4+4
  
  flutter_lints: ^1.0.0
  
flutter:               
  assets:     
          - assets/
          - assets/imgs/fruits.png
          - assets/imgs/welcomeimage.jpg
          - assets/imgs/
          - assets/imgs/sidebar.jpg
          - assets/imgs/profe.jpg

  uses-material-design: true